baseurl = "https://conorfleming.github.io/"
title = "Conor Fleming"
copyright = "&copy; 2016 Conor Fleming"
languageCode = "en-us"
theme = "academic"

# Enable comments by entering your Disqus shortname
# disqusShortname = "spf13"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "58468306"


[params]
  name = "Conor Fleming"
  role = "Mechanical Engineer"
  organization = "Atkins"
  avatar = "cfleming_id.jpg"
  email = "conor.fleming@oxon.org"
  address = "Epsom, UK"
  phone = ""

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []


  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:conor.fleming@oxon.org"

#  [[params.social]]
#    icon = "twitter"
#    icon_pack = "fa"
#    link = "//twitter.com/GeorgeCushen"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/drconorfleming"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "//scholar.google.co.uk/citations?user=J4rZ7wgAAAAJ&hl=en&oi=ao"


# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Publications & Talks"
  url = "#publications"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 4
